# Navigation Links
main:
  - name: Home
    url: /
    weight: 10
  - name: Experience
    url: /#experience
    weight: 20
  - name: Skills
    url: /#skills
    weight: 30
  - name: Publications
    url: /#publications
    weight: 40
  - name: CV
    url: https://drive.google.com/open?id=1zdJIzxfl8LTjYx-GNwI48st9i9fEnhvx&usp=drive_fs
    weight: 50
